"""add_tenant_id

Revision ID: 57fc3e78cc23
Revises: 4b1e29c9ae76
Create Date: 2026-08-17 23:26:16.862843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57fc3e78cc23'
down_revision: Union[str, Sequence[str], None] = '4b1e29c9ae76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_items', sa.Column('cnae', sa.String(length=20), nullable=True))
    op.alter_column('invoice_items', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('invoice_items', 'unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('invoice_items', 'total_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
    op.drop_column('invoice_items', 'cfop')
    op.drop_column('invoice_items', 'ncm')
    op.drop_column('invoice_items', 'product_code')
    op.add_column('invoices', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.add_column('invoices', sa.Column('competence_date', sa.DateTime(), nullable=True))
    op.add_column('invoices', sa.Column('verification_code', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('issuer_im', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('service_municipality', sa.String(length=255), nullable=True))
    op.add_column('invoices', sa.Column('gross_value', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('net_value', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('calculation_base', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('iss_value', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('iss_retained', sa.Boolean(), nullable=True))
    op.add_column('invoices', sa.Column('ir_value', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('csll_value', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('inss_value', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('pis_value', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('cofins_value', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('national_tax_code', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('lc116_code', sa.String(length=20), nullable=True))
    op.add_column('invoices', sa.Column('service_description', sa.Text(), nullable=True))
    op.alter_column('invoices', 'access_key',
               existing_type=sa.VARCHAR(length=44),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_index(op.f('ix_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    op.drop_column('invoices', 'discount')
    op.drop_column('invoices', 'freight')
    op.drop_column('invoices', 'products_total')
    op.drop_column('invoices', 'total_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('total_value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('products_total', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('freight', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('discount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_invoices_tenant_id'), table_name='invoices')
    op.alter_column('invoices', 'access_key',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=44),
               existing_nullable=True)
    op.drop_column('invoices', 'service_description')
    op.drop_column('invoices', 'lc116_code')
    op.drop_column('invoices', 'national_tax_code')
    op.drop_column('invoices', 'cofins_value')
    op.drop_column('invoices', 'pis_value')
    op.drop_column('invoices', 'inss_value')
    op.drop_column('invoices', 'csll_value')
    op.drop_column('invoices', 'ir_value')
    op.drop_column('invoices', 'iss_retained')
    op.drop_column('invoices', 'iss_value')
    op.drop_column('invoices', 'calculation_base')
    op.drop_column('invoices', 'net_value')
    op.drop_column('invoices', 'gross_value')
    op.drop_column('invoices', 'service_municipality')
    op.drop_column('invoices', 'issuer_im')
    op.drop_column('invoices', 'verification_code')
    op.drop_column('invoices', 'competence_date')
    op.drop_column('invoices', 'tenant_id')
    op.add_column('invoice_items', sa.Column('product_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('invoice_items', sa.Column('ncm', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('invoice_items', sa.Column('cfop', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.alter_column('invoice_items', 'total_price',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('invoice_items', 'unit_price',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('invoice_items', 'description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('invoice_items', 'cnae')
    # ### end Alembic commands ###
