"""add_audit_and_task

Revision ID: 6eb773af39bc
Revises: 7c7dfbc1f938
Create Date: 2026-08-13 22:56:42.214893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eb773af39bc'
down_revision: Union[str, Sequence[str], None] = '7c7dfbc1f938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('imported_by', sa.String(length=255), nullable=True))
    op.add_column('invoices', sa.Column('imported_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'imported_at')
    op.drop_column('invoices', 'imported_by')
    # ### end Alembic commands ###
