"""Criando tabelas de notas fiscais e itens

Revision ID: 7c7dfbc1f938
Revises: 
Create Date: 2026-08-13 16:16:03.619587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c7dfbc1f938'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('access_key', sa.String(length=44), nullable=True),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('series', sa.String(length=10), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.Column('issuer_cnpj', sa.String(length=14), nullable=True),
    sa.Column('issuer_name', sa.String(length=255), nullable=True),
    sa.Column('recipient_cnpj', sa.String(length=14), nullable=True),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('products_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('freight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_access_key'), 'invoices', ['access_key'], unique=True)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_issuer_cnpj'), 'invoices', ['issuer_cnpj'], unique=False)
    op.create_index(op.f('ix_invoices_number'), 'invoices', ['number'], unique=False)
    op.create_index(op.f('ix_invoices_recipient_cnpj'), 'invoices', ['recipient_cnpj'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('ncm', sa.String(length=10), nullable=True),
    sa.Column('cfop', sa.String(length=10), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_id'), 'invoice_items', ['id'], unique=False)
    op.drop_index(op.f('ix_processed_documents_file_type'), table_name='processed_documents')
    op.drop_index(op.f('ix_processed_documents_id'), table_name='processed_documents')
    op.drop_table('processed_documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('processed_documents_pkey'))
    )
    op.create_index(op.f('ix_processed_documents_id'), 'processed_documents', ['id'], unique=False)
    op.create_index(op.f('ix_processed_documents_file_type'), 'processed_documents', ['file_type'], unique=False)
    op.drop_index(op.f('ix_invoice_items_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_invoices_recipient_cnpj'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_issuer_cnpj'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_access_key'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
